### ISSUE TITLE
Sometimes the same color scheme is applied to both maps

### ISSUE THREAD

**Issue by jwwood3** [hdc-arizona/GardenMockups#25]
Whenever data is loaded onto both maps simultaneously, it renders both maps with the colors for the map that started loading second.

I believe this is caused by the populateMap function which sets the state variable colors to the appropriate set based on the map being loaded. When one map starts loading after the other, this state variable is changed. Then, when both maps are rendered, they reference this same variable.

@TT1603 @kisaacs

**Comment by tt-016** [comment]
I fixed how we store the colors a bit, and it shows no problem on my side. Would you have a look at the PR and see if it works now?
