### ISSUE TITLE
Remove white outline from shapes in map.

### ISSUE THREAD

**Issue by kisaacs** [hdc-arizona/GardenMockups#29]
When we're zoomed out, the white outlines make all of Tucson and Phoenix look white. Perhaps we should just not draw them at any scale unless that particular shape is selected. 

@TT1603

**Comment by tt-016** [comment]
I removed the map outline, so now they will only have outlines on hovering and clicking.

But I think we have another problem. Somehow there are tracts that are not colored even though there is data on them, so they just appear black.

**Comment by kisaacs** [comment]
Thanks Thu. I'll close this and add this issue to the data values one. Closed by #30
